Add aurora serverlessv2 support
cloudposse/terraform-aws-rds-cluster pull request #138
Opened 2022-04-30 12:05 UTC by topikachu

## what
* Add aurora serverlessv2 support

## why
* AWS releases aurora serverless v2.  
* Adopt this new feature in this rds cluster module

## references
*  closes #137
* [Terraform serverlessv2_scaling_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#serverlessv2_scaling_configuration)

2022-05-03 23:41 UTC, Gowiem commented
/test all

2022-05-03 23:47 UTC, Gowiem commented on main.tf
> +
```suggestion
```

2022-05-03 23:47 UTC, Gowiem commented on main.tf
> +
```suggestion
```

2022-05-04 00:10 UTC, Gowiem commented
/test all

2022-05-04 00:40 UTC, Gowiem commented
@topikachu @kevcube this would require [AWS Provider v4.12.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4120-april-28-2022)+. 

Will have to chat with the team about if we're ready to bump this module to the v4+ provider.

2022-05-12 01:46 UTC, topikachu commented
> @topikachu @kevcube this would require [AWS Provider v4.12.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4120-april-28-2022)+.
> 
> Will have to chat with the team about if we're ready to bump this module to the v4+ provider.

Thanks.
If it's difficult to upgrade to the new v4+, is it possible to publish a new major version (even beta) instead of replacing the old one?
Or at least to a new git branch so I can use the offically one instead of mine. ^-^

2022-05-23 21:50 UTC, Nuru commented
@topikachu Would you please add a test for this? You can pretty much duplicate `examples/complete` and `test/src/examples_complete_test.go`, rename "complete" to "serverlessv2" and flip on the new option in the new test.

2022-05-27 00:24 UTC, alexjurkiewicz commented
Hey @topikachu. Are you still working on this PR? I will take it over if not 🙌

2022-05-29 13:40 UTC, topikachu commented
> Hey @topikachu. Are you still working on this PR? I will take it over if not 🙌

I'm here. Will add tests as you suggest.

2022-05-30 06:11 UTC, topikachu commented
> Hey @topikachu. Are you still working on this PR? I will take it over if not 🙌

Done!
A lot to change because I have to upgrade AWS provider version and others.
Hope this doesn't break others too much.

Test by `make clean test`.

2022-06-03 22:40 UTC, Nuru commented
/test all

2022-06-03 23:04 UTC, Nuru requested changes
Don't worry about the test failures from the previous run.

2022-06-04 17:19 UTC, Nuru commented
/test all

2022-06-04 17:51 UTC, Nuru commented on examples/complete/main.tf
> +  version = "2.0.2"
`dynamic-subnets` v2 requires Terraform version `>= 1.1.0`. Please update `versions.tf` accordingly

2022-06-04 18:00 UTC, Nuru commented
/test all

2022-06-10 14:54 UTC, joshmello commented on main.tf
> +  dynamic "serverlessv2_scaling_configuration" {
Would setting the default variable value for `storage_encrypted` to `true` fix these issues?

2022-06-12 01:08 UTC, topikachu commented on main.tf
> +  dynamic "serverlessv2_scaling_configuration" {
> storage_encrypted

I believe this setting is caused by the old serverless configuration.
Shall we just work on the serverlessv2_scaling_configuration in this PR?

We can clean the old serverless later if required.

2022-06-12 13:18 UTC, joshmello commented on main.tf
> +  dynamic "serverlessv2_scaling_configuration" {
imo yes, they support encryption anyways @Nuru any thoughts?

2022-06-13 05:17 UTC, Nuru commented
/test all

2022-06-13 05:28 UTC, Nuru approved these changes
The  `bats` test failure is due to formatting differences among Terraform versions, and inconsistency in what the actions format with vs what the actions test with. Ignoring it for now.

Marking this version as `no-release` so we can release it as version 1.0, per Cloud Posse migration to production semantic versioning.

2022-06-13 05:47 UTC, merged

2022-06-15 23:39 UTC, topikachu commented
@Nuru  I'm happy that this change is merged into the upstream.
I'd like to know if there's any timeline to release this version? So I can use the official cloudposse module in my project.

Thanks

2022-06-15 23:56 UTC, kevcube commented
@topikachu it is released

https://github.com/cloudposse/terraform-aws-rds-cluster/releases/tag/1.0.0