Support for Activity Stream added
cloudposse/terraform-aws-rds-cluster pull request #159
Opened 2023-02-26 06:27 UTC by ngoyal16

## what
* Allow to create Activity Stream for RDS Cluster

## why
* Can be used to enable and activity stream from the cluster module itself

2023-02-27 13:05 UTC, goruha commented
@ngoyal16 Thanks for the PR.
Can you also add outputs for stream
`kinesis_stream_name` and `id`

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_activity_stream#attributes-reference

2023-02-27 13:07 UTC, goruha requested changes
Needs activity stream outputs

2023-02-27 13:08 UTC, goruha commented
/test all

2023-02-27 13:11 UTC, goruha commented
@ngoyal16 Tests failed 

```
╷
│ Error: Missing resource instance key
│ 
│   on main.tf line 401, in resource "aws_rds_cluster_activity_stream" "primary":
│  401:   resource_arn = aws_rds_cluster.primary.arn
│ 
│ Because aws_rds_cluster.primary has "count" set, its attributes must be
│ accessed on specific instances.
│ 
│ For example, to correlate with indices of a referring resource, use:
│     aws_rds_cluster.primary[count.index]
```

2023-02-27 15:07 UTC, ngoyal16 commented
/test all

2023-02-27 15:08 UTC, ngoyal16 commented
@goruha i have added the outputs. also fix the issue related to cluster arn

2023-02-27 17:35 UTC, jamengual commented
/test all

2023-02-28 02:02 UTC, ngoyal16 commented
@jamengual or @goruha can you help me to understand why the test cases has failed so that i can fix them.

2023-02-28 02:07 UTC, ngoyal16 commented
can you please provide the steps to do it.?

2023-02-28 02:13 UTC, jamengual commented
can you see the failing checks? you can google the error, sorry I'm on my phone

2023-02-28 02:41 UTC, ngoyal16 commented
@jamengual i have tried all solution found on google but no luck

2023-02-28 02:48 UTC, jamengual commented
/test all

2023-02-28 03:53 UTC, jamengual commented
run 
```make init
make readme
terraform fmt
``` 

and then add and commit the files.

2023-03-01 02:11 UTC, ngoyal16 commented
@jamengual please check now

2023-03-01 02:20 UTC, jamengual commented
/test all

2023-03-01 03:26 UTC, jamengual commented
to fig the issue you need to run one more command :

 make init
 make github/init

2023-03-01 06:15 UTC, ngoyal16 commented
@jamengual  i have updated the code as pre requirement.

2023-03-01 06:34 UTC, jamengual commented
/test all

2023-03-01 08:10 UTC, goruha commented
/test all

2023-03-01 08:47 UTC, ngoyal16 commented
/test all

2023-03-01 13:14 UTC, ngoyal16 commented
@goruha what could be the reason of failure?

2023-03-01 15:22 UTC, dudymas commented
It looks like [VPC limit](https://github.com/cloudposse/actions/actions/runs/4301391120/jobs/7498567681#step:9:1841) is the issue

2023-03-01 17:41 UTC, jamengual commented
/test all

2023-03-02 02:18 UTC, ngoyal16 commented
@jamengual  can you please try again

2023-03-02 05:11 UTC, jamengual commented
/test all

2023-03-02 06:31 UTC, jamengual commented
/test terratest

2023-03-02 17:13 UTC, jamengual commented
/test all

2023-03-02 17:17 UTC, jamengual commented
@ngoyal16 I ping CloudPosse to see if they can bump up the vpc count.

2023-03-02 23:02 UTC, ngoyal16 commented
@jamengual  thank you for your effort.

2023-03-03 14:09 UTC, ngoyal16 commented
@jamengual any update on same?

2023-03-03 19:17 UTC, jamengual commented
/test all

2023-03-03 22:07 UTC, jamengual commented
/test all

2023-03-05 08:22 UTC, jamengual commented
/test all

2023-03-06 20:16 UTC, jamengual commented
/test all

2023-03-07 14:07 UTC, nitrocode commented on main.tf
> +  resource_arn = aws_rds_cluster.primary[0].arn
```suggestion
  resource_arn = one(aws_rds_cluster.primary[*].arn)
```

2023-03-07 14:09 UTC, nitrocode submitted a review, later dismissed

2023-03-07 14:10 UTC, nitrocode commented
/test all

2023-03-09 05:16 UTC, ngoyal16 commented
@goruha or @jamengual can you please retest?

2023-03-09 05:25 UTC, joe-niland commented
/test terratest

2023-03-09 05:54 UTC, joe-niland commented
@ngoyal16 the VPC limit issue still needs to be addressed

2023-03-09 20:46 UTC, Nuru commented
/test terratest

2023-03-09 21:20 UTC, Nuru commented
/test all

2023-03-09 21:50 UTC, Nuru commented
/test all

2023-03-09 23:06 UTC, Nuru commented
/test all

2023-03-10 01:44 UTC, Nuru commented
/test all

2023-03-10 02:43 UTC, Nuru approved these changes
Restoring @nitrocode's stale approval

2023-03-10 02:43 UTC, merged