Global fixes
cloudposse/terraform-aws-rds-cluster pull request #89
Opened 2020-10-23 14:09 UTC by hibbert

## what

Currently for a secondary cluster with this module you get the following error:

```
Error: error creating RDS cluster: InvalidParameterCombination: Cannot specify user name for cross region replication cluster
```

This cannot be worked around as `admin_user` has a default of "admin", this sets the default to an empty string 

## why
* So can have a global cluster

## references
* N/A

2020-10-23 17:22 UTC, Nuru commented
/test all

2020-10-23 17:47 UTC, Nuru commented
/rebuild-readme

2020-10-23 17:54 UTC, Nuru requested changes

2020-10-23 17:54 UTC, Nuru commented on variables.tf
> +  default     = ""
```suggestion
  default     = "admin"
```
To preserve backwards compatibility, we do not want to change default values.

2020-10-28 12:05 UTC, hibbert commented
No worries, was able to set `admin_user=""`

2020-10-28 12:05 UTC, closed without merging