Cloudposse master
cloudposse/terraform-aws-rds-cluster pull request #94
Opened 2020-12-05 09:28 UTC by rverma-jm

## what
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.

## why
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.

## references
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow). 
* Use `closes #123`, if this PR closes a GitHub issue `#123`

2020-12-05 20:07 UTC, joe-niland commented
@rverma-jm thanks for the PR. Please update PR title and description so it's clear what it's for.

2020-12-06 02:27 UTC, aknysh commented
@rverma-jm  thanks for the PR, please update the `what` and `why` so we understand what is being changed and why

2020-12-09 18:28 UTC, jamengual commented on main.tf
> -resource "aws_rds_cluster" "primary" {
Changing the resource name will destroy every single cluster already created using this module, this is a not needed breaking change.

2020-12-13 10:10 UTC, Nuru requested changes
- Fill in the PR description
- Restore the "primary" name. 
- Validate that the log groups work as expected with all database engine types
- Make other changes as noted in comments

2020-12-13 10:10 UTC, Nuru commented on main.tf
> +  name              = "/aws/rds/cluster/${coalesce(join("", aws_rds_cluster.default.*.id), join("", aws_rds_cluster.secondary.*.id))}/postgresql"
I am not completely sure how log groups work with primary and secondary clusters. According to [this documentation](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.CloudWatch.html#AuroraPostgreSQL.CloudWatch.Monitor) you need a log group per log type anyway.

```suggestion
  for_each          = module.this.enabled ? toset(var.enabled_cloudwatch_logs_exports) : []
  name              = "/aws/rds/cluster/${coalesce(join("", aws_rds_cluster.primary.*.id), join("", aws_rds_cluster.secondary.*.id))}/${each.value}"
```

Also, update description of `var.enabled_cloudwatch_logs_exports` to include `postgresql` in the list of valid log types.

2021-02-09 06:18 UTC, Nuru commented
Closing this as unclear on the purpose and apparently abandoned by the OP. Can be reopened if `what` and `why` are filled in and other comments addressed.

2021-02-09 06:18 UTC, closed without merging